version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            net:
              ipv4_address: 10.0.0.10
        ports:
            - "8000:8000"
        depends_on:
            - postgresql
            - mongodb
            - redis
            - rabbitmq
    postgresql:
      image: postgres
      container_name: postgres
      restart: always
      networks:
          net:
              ipv4_address: 10.0.0.20
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: mydatabase
        POSTGRES_HOST_AUTH_METHOD: trust
      volumes:
          - postgresql-data:/var/lib/postgresql/data
      ports:
          - "5432:5432"

    mongodb:
      image: mongo
      container_name: mongodb
      restart: always
      networks:
          net:
              ipv4_address: 10.0.0.30
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      volumes:
          - mongodb-data:/data/db
      ports:
         - "27017:27017"

    redis:
      image: redis
      container_name: redis
      restart: always
      networks:
          net:
              ipv4_address: 10.0.0.40
      volumes:
          - redis-data:/data
      ports:
        - "6379:6379"

    rabbitmq:
      image: rabbitmq
      container_name: rabbitmq
      restart: always
      networks:
          net:
              ipv4_address: 10.0.0.50
      environment:
        RABBITMQ_DEFAULT_USER: root
        RABBITMQ_DEFAULT_PASS: root
      ports:
       - "5672:5672"
       - "15672:15672"

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgAdmin
      networks:
          net:
              ipv4_address: 10.0.0.60
      ports:
        - "5050:80"
      depends_on:
        - postgresql
      environment:
        PGADMIN_DEFAULT_EMAIL: arkadiusz.jaswiec@edu.wsti.pl
        PGADMIN_DEFAULT_PASSWORD: root

networks:
      net:
        ipam:
          config:
              - subnet: 10.0.0.0/24

volumes:
    postgresql-data:
    mongodb-data:
    redis-data:
    rabbitmq-data:
