version: '3'
services:
    postgresql:
      image: postgres
      container_name: postgres
      restart: always
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: mydatabase
      volumes:
          - postgresql-data:/var/lib/postgresql/data
      ports:
          - "5432:5432"

    mongodb:
      image: mongo
      container_name: mongodb
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      volumes:
          - mongodb-data:/data/db
      ports:
         - "27017:27017"

    redis:
      image: redis
      container_name: redis
      restart: always
      volumes:
          - redis-data:/data
      ports:
        - "6379:6379"

    rabbitmq:
      image: rabbitmq
      container_name: rabbitmq
      restart: always
      environment:
        RABBITMQ_DEFAULT_USER: root
        RABBITMQ_DEFAULT_PASS: root
      ports:
       - "5672:5672"
       - "15672:15672"

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgAdmin
      ports:
        - "5050:80"
      depends_on:
        - postgresql
      environment:
        PGADMIN_DEFAULT_EMAIL: arkadiusz.jaswiec@edu.wsti.pl
        PGADMIN_DEFAULT_PASSWORD: root

volumes:
    postgresql-data:
    mongodb-data:
    redis-data:
    rabbitmq-data:
